services:
  postgres:
    image: postgres:15
    container_name: wallets_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wallet-net
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallets_app
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/,file:/app/config/
    networks:
      - wallet-net
    restart: on-failure

volumes:
  pgdata:

networks:
  wallet-net:
