version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wallets_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wallet-net
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallets_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallets
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - wallet-net
    restart: on-failure

volumes:
  pgdata:

networks:
  wallet-net:
